config/routes.rb
AccessControlLite::Application.routes.draw do
  resources :accesses do
    get :autocomplete_user_name, :on => :collection
    get :autocomplete_system_name, :on => :collection
   
  end
match 'accesses/:id/authorise' => 'accesses#authorise', :as => :authorise
match 'accesses/:id/action' => 'accesses#action', :as => :action_request
  resources :user_control

  resources :systems do
    get :autocomplete_user_name, :on => :collection
    resources :access_levels
    post 'get_alevels', :on => :member
  end

  devise_for :users

  root :to => "home#index"

end

app/controllers/user_control_controller.rb
class UserControlController < ApplicationController

def index
@users = User.page(params[:page])
   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
end

# GET /systems/1
  # GET /systems/1.json
  def show
    @user = User.find(params[:id])
    @accesses = Access.where(:user_id => @user.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system }
    end
  end

end

app/helpers/user_control_helper.rb
module UserControlHelper
end

app/views/user_control/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/user_control/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", systems_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_system_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Systems
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.system.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @users.each do |user|
          %tr{:class => cycle("odd", "even")}
            %td
              = user.id
            %td
              = link_to user.name, user_control_path(user)
            %td
              = user.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", user_control_path(user)
              |

      .actions-bar.wat-cf
        .actions
        = paginate @users
- content_for :sidebar, render(:partial => 'sidebar')

app/views/user_control/show.html.haml
#block-text.block
  .content
    %h2.title 
      = @user.name
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.system.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @accesses.each do |access|
          %tr{:class => cycle("odd", "even")}
            %td
              = access.user.name
            %td
              = access.system.name
            %td
              = access.authoriser.name
      %p
        %span.small Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %p
        %span.gray Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %hr/
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
- content_for :sidebar, render(:partial => 'sidebar')