config/routes.rb
AccessControlLite::Application.routes.draw do
  resources :accesses do
    get :autocomplete_user_name, :on => :collection
    get :autocomplete_system_name, :on => :collection
   
  end
match 'accesses/:id/authorise' => 'accesses#authorise', :as => :authorise
match 'accesses/:id/action' => 'accesses#action', :as => :action_request
  resources :user_control

  resources :systems do
    get :autocomplete_user_name, :on => :collection
    resources :access_levels
    post 'get_alevels', :on => :member
  end

  devise_for :users

  root :to => "home#index"

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  autocomplete :user, :name
  autocomplete :system, :name
  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.page(params[:page])
    systems = System.where(:owner_id => current_user.id )
    action_systems = System.where("admin1_id = ? OR admin2_id = ?", current_user.id,current_user.id)
    @authorise_me = Access.where("system_id IN (?) AND authorised_by IS NULL",systems).page(params[:page])
    @action_me = Access.where("system_id IN (?) AND authorised_by IS NOT NULL AND actioned_by IS NULL", action_systems).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accesses }
    end
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
    @access = Access.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access }
    end
  end

  # GET /accesses/new
  # GET /accesses/new.json
  def new
    @access = Access.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @access }
    end
  end

  # GET /accesses/1/edit
  def edit
    @access = Access.find(params[:id])
  end

  def authorise
    @access = Access.find(params[:id])
    if @access.system.owner_id == current_user.id
      @access.authorised_by = current_user
      @access.authorised_date =  Date.current

    else
      @access.errors.add "You're not the system owner - gerrof!"
    end

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render json: @access, status: :created, location: @access }
      else
        format.html { render action: "new" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  def action
    @access = Access.find(params[:id])
    if request.get?
      
      render partial:  'action_request' , :locals => { :ac => @access}
    end
    if request.put?
      if @access.update_attributes(params[:access])
        @access.actioned_by = current_user.id
        @access.actioned_date = Date.current
        @access.save()
      end
      if 
        ready = { :ready => true }
      else
        ready = { :ready => false }
      end
      render json: ready
    end
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(params[:access])

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render json: @access, status: :created, location: @access }
      else
        format.html { render action: "new" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accesses/1
  # PUT /accesses/1.json
  def update
    @access = Access.find(params[:id])

    respond_to do |format|
      if @access.update_attributes(params[:access])
        format.html { redirect_to @access, notice: 'Access was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access = Access.find(params[:id])
    @access.destroy

    respond_to do |format|
      format.html { redirect_to accesses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_action_request.html.haml
.block.notice.whiteout
	%h3 Access Provision Details
	%br
		.content
			= form_for ac, :url => action_request_path, :remote => true ,:html => { :class => :form } do |f|
				.group
					= f.label :username, "User Name", :class => :label
					= f.text_field :username, :class => 'text_field'
					
				.group
					= f.label :temp_password, "Temporary Password", :class => :label
					= f.text_field :temp_password, :class => 'text_field'
					
				= f.submit 'Provision'

app/views/accesses/_form.html.haml
.group
  = f.label :user_id, t("activerecord.attributes.access.user_id", :default => "User"), :class => :label
  = f.hidden_field :user_id
  = autocomplete_field_tag 'user','', autocomplete_user_name_accesses_path, :id_element => '#access_user_id'
  %span.description Ex: a simple text

.group
  = f.label :system_id, t("activerecord.attributes.access.user_id", :default => "System"), :class => :label
  = f.hidden_field :system_id
  = autocomplete_field_tag 'system','', autocomplete_system_name_accesses_path, :id_element => '#access_system_id'
  %span.description Ex: a simple text

.group
  = f.label :level_id, t("activerecord.attributes.access.level_id", :default => "Level"), :class => :label
  = f.select :level_id, ''
  %span.description Ex: a simple text


.group
  = f.label :request_date, t("activerecord.attributes.access.request_date", :default => "Request date"), :class => :label
  = f.date_select :request_date, :class => 'date_select'
  %span.description Ex: a simple text

.group
  = f.label :reason, t("activerecord.attributes.access.reason", :default => "Reason"), :class => :label
  = f.text_area :reason, :class => 'text_area'
  %span.description Provide a brief reason as to why the user requires this access
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), accesses_path, :class => "text_button_padding link_button"

app/views/accesses/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2
.block.action_request

app/views/accesses/action.js.erb
$('.block.notice.whiteout').html(' Done ')
$('.block.notice.whiteout').fadeOut(1000)
$('tr.access_request.'+ @access.id).fadeOut(1000)

app/views/accesses/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", accesses_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_access_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_access_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Access
    .inner
      = form_for @access, :url => access_path(@access), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/accesses/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", accesses_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_access_path
  .content
    %h2.title
      Access Requests Requiring Your Approval
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.access.user_id", :default => t("activerecord.labels.user_id", :default => "User"))
          %th= t("web-app-theme.reason", :default => "Reason")
          %th.last &nbsp;
        - @authorise_me.each do |access|
          %tr{:class => cycle("odd", "even")}
            %td
              = access.id
            %td
              = link_to access.user.name, access_path(access)
            %td
              = access.reason

            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", access_path(access)
              = link_to image_tag( 'authorise.png '), authorise_path(access)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_access_path(access)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", access_path(access), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @accesses

    %h2.title
      
      Access Requests Requiring Your Action
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.access.user_id", :default => t("activerecord.labels.user_id", :default => "User_id"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @action_me.each do |access|
          .action_request{:class=>access.id}
            %tr{:class => [cycle("odd", "even"),'access_request',access.id]}
              %td
                = access.id
              %td
                = link_to access.user_id, access_path(access)
              %td
                = access.created_at
              %td.last
                = link_to "#{t("web-app-theme.show", :default => "Show")}", access_path(access)
                |
                \#{link_to "Action",'#', :class => 'action_request', :'data-id' => access.id} 
                |
                \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_access_path(access)} 

                \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", access_path(access), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
    

        = paginate @accesses
    %h2.title
      
      Outstanding Access Requests For People You Manage
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.access.user_id", :default => t("activerecord.labels.user_id", :default => "User_id"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @accesses.each do |access|
          %tr{:class => cycle("odd", "even")}
            %td
              = access.id
            %td
              = link_to access.user_id, access_path(access)
            %td
              = access.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", access_path(access)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_access_path(access)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", access_path(access), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
    
        = paginate @accesses
     
  
- content_for :sidebar, render(:partial => 'sidebar')

app/views/accesses/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", accesses_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_access_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Access Request
    .inner
      = form_for :access, :url => accesses_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/accesses/new.js.haml
//test

app/views/accesses/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", accesses_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_access_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", access_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.access.user_id", :default => t("activerecord.labels.user_id", :default => "User"))
          \:
        = @access.user_id
      %p
        %b
          = t("activerecord.attributes.access.level_id", :default => t("activerecord.labels.level_id", :default => "Level"))
          \:
        = @access.level_id
      %p
        %b
          = t("activerecord.attributes.access.request_date", :default => t("activerecord.labels.request_date", :default => "Request date"))
          \:
        = @access.request_date
      %p
        %b
          = t("activerecord.attributes.access.authorised_by", :default => t("activerecord.labels.authorised_by", :default => "Authorised by"))
          \:
        = @access.authorised_by
      %p
        %b
          = t("activerecord.attributes.access.authorised_date", :default => t("activerecord.labels.authorised_date", :default => "Authorised date"))
          \:
        = @access.authorised_date
      %p
        %b
          = t("activerecord.attributes.access.actioned_by", :default => t("activerecord.labels.actioned_by", :default => "Actioned by"))
          \:
        = @access.actioned_by
      %p
        %b
          = t("activerecord.attributes.access.actioned_date", :default => t("activerecord.labels.actioned_date", :default => "Actioned date"))
          \:
        = @access.actioned_date
      %p
        %b
          = t("activerecord.attributes.access.username", :default => t("activerecord.labels.username", :default => "Username"))
          \:
        = @access.username
      %p
        %b
          = t("activerecord.attributes.access.temp_password", :default => t("activerecord.labels.temp_password", :default => "Temp password"))
          \:
        = @access.temp_password
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_access_path(@access), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), access_path(@access), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')