config/routes.rb
AccessControlLite::Application.routes.draw do
  resources :accesses do
    get :autocomplete_user_name, :on => :collection
    get :autocomplete_system_name, :on => :collection
   
  end
match 'accesses/:id/authorise' => 'accesses#authorise', :as => :authorise
match 'accesses/:id/action' => 'accesses#action', :as => :action_request
  resources :user_control

  resources :systems do
    get :autocomplete_user_name, :on => :collection
    resources :access_levels
    post 'get_alevels', :on => :member
  end

  devise_for :users

  root :to => "home#index"

end

app/models/system.rb
class System < ActiveRecord::Base
	paginates_per 5
	has_many :access_levels
	has_many :accesses
	belongs_to :owner , :foreign_key => 'owner_id' , :class_name => 'User'
	belongs_to :admin1 , :foreign_key => 'admin1_id', :class_name => 'User'
	belongs_to :admin2 , :foreign_key => 'admin2_id', :class_name => 'User'

	accepts_nested_attributes_for :access_levels, :allow_destroy => true, :reject_if => :reject_al_destroy

	def reject_al_destroy(attributed)
		if attributed['_destroy'] == 1
			Access.where(:level_id => attributed['id'])
			return true
		else
			return false
		end
	end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  autocomplete :user, :name
  # GET /systems
  # GET /systems.json
  def index
    @systems = System.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @systems }
    end
  end

  def get_alevels
    @system = System.find(params[:id])

    @alevels = @system.access_levels

    render json: @alevels
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
    @system = System.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/new
  # GET /systems/new.json
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(params[:system])

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render json: @system, status: :created, location: @system }
      else
        format.html { render action: "new" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1
  # PUT /systems/1.json
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to systems_url }
      format.json { head :ok }
    end
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.haml
.group
  = f.label :name, t("activerecord.attributes.system.name", :default => "Name"), :class => :label
  = f.text_field :name, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :description, t("activerecord.attributes.system.description", :default => "Description"), :class => :label
  = f.text_area :description, :class => 'text_area'
  %span.description Ex: a simple text
.group
  = f.label :owner_id, t("activerecord.attributes.system.owner_id", :default => "Owner"), :class => :label
  = f.hidden_field :owner_id
  = autocomplete_field_tag 'owner',(@system.owner.name unless @system.owner.blank?) ,autocomplete_user_name_systems_path, :id_element => '#system_owner_id'
  %span.description Ex: a simple text

.group
  = f.label :owner_id, "Access Levels" , :class => :label

  = f.fields_for :access_levels do |alform|
    %span.text_field 
      = alform.text_field :name, :style => 'margin-top: 5px;'
      = alform.link_to_remove "Remove"
  = f.link_to_add "Add Access Level", :access_levels
.group
  = f.label :admin_1, t("activerecord.attributes.system.owner_id", :default => "Primary Admin"), :class => :label
  = f.hidden_field :admin1_id
  = autocomplete_field_tag 'admin2',(@system.admin1.name unless @system.admin1.blank?) , autocomplete_user_name_systems_path, :id_element => '#system_admin1_id'
  %span.description Ex: a simple text
.group
  = f.label :admin_2, t("activerecord.attributes.system.owner_id", :default => "Secondary Admin"), :class => :label
  = f.hidden_field :admin2_id
  = autocomplete_field_tag 'admin1',(@system.admin2.name unless @system.admin2.blank?) , autocomplete_user_name_systems_path, :id_element => '#system_admin2_id'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), systems_path, :class => "text_button_padding link_button"

app/views/systems/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/systems/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", systems_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_system_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_system_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      System
    .inner
      = nested_form_for @system, :url => system_path(@system), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/systems/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", systems_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_system_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Systems
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.system.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @systems.each do |system|
          %tr{:class => cycle("odd", "even")}
            %td
              = system.id
            %td
              = link_to system.name, system_path(system)
            %td
              = system.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", system_path(system)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_system_path(system)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", system_path(system), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @systems
- content_for :sidebar, render(:partial => 'sidebar')

app/views/systems/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", systems_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_system_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      System
    .inner
      = nested_form_for @system, :url => systems_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/systems/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", systems_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_system_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", system_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.system.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @system.name
      %p
        %b
          = t("activerecord.attributes.system.description", :default => t("activerecord.labels.description", :default => "Description"))
          \:
        = @system.description
      %p
        %b
          = t("activerecord.attributes.system.owner_id", :default => t("activerecord.labels.owner_id", :default => "Owner"))
          \:
        = @system.owner.name
      %p
        %b
          = t("activerecord.attributes.system.admin1_id", :default => t("activerecord.labels.admin1_id", :default => "Admin1"))
          \:
        = @system.admin1_id
      %p
        %b
          = t("activerecord.attributes.system.admin2_id", :default => t("activerecord.labels.admin2_id", :default => "Admin2"))
          \:
        = @system.admin2_id
      %p
        %b
          Access Levels
          \:
          = @system.access_levels.collect{|acl| acl.name}.join(',')
            
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_system_path(@system), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), system_path(@system), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')